Adding, removing and sorting elements   

In [1]:
import numpy as np

In [2]:
first_arr = np.array([1,2])
new_arr = np.insert(first_arr, 1,4)
new_arr


                    


array([1, 4, 2])

In [4]:
second_arr = np.array([2,4,1])
second_arr = np.append(second_arr, 5)
second_arr

array([2, 4, 1, 5])

In [5]:
second_arr = np.delete(second_arr, 2)
second_arr

array([2, 4, 5])

In [15]:
ints_2dim = np.array([[3,2,5,7], [5,0,8,3]])
ints_2dim

array([[3, 2, 5, 7],
       [5, 0, 8, 3]])

In [16]:
print(np.sort(ints_2dim))

[[2 3 5 7]
 [0 3 5 8]]
