Aggregate Functions


In [1]:
import numpy as np

In [5]:
fa = np.arange(10,130,10)
fa

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [3]:
sa = np.arange(10,100,10).reshape(3,3)
sa

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
ta = np.arange(10,110,10).reshape(2,5)
ta

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [5]:
fa.sum()

np.int64(550)

In [6]:
sa.sum(axis=0)

array([120, 150, 180])

In [7]:
#summ of each row
sa.sum(axis=1)

array([ 60, 150, 240])

In [11]:
ar1=np.arange(1,10).reshape(3,3)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
ar2=np.arange(11,21).reshape(2,5)
ar2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
ar2.prod()

np.int64(670442572800)