Copies and views


In [1]:
import numpy as np

Assignment != Copy -> It copies the reference to memory of the numpy object

In [2]:
stud_num = np.array([1,2,3])
stud_num2 = stud_num
print(stud_num2)
stud_num2[1] = 4
print(stud_num2)
print(stud_num)     

[1 2 3]
[1 4 3]
[1 4 3]


For copy -> use only copy()

In [5]:
stud_num2 = stud_num.copy()
stud_num2[1] = 20
print(stud_num2)
print(stud_num)

[ 1 20  3]
[1 4 3]


In [7]:
view_arr = np.array([10,20,30,40,50])
view = view_arr[1:4]
view
print(view.base)

[10 20 30 40 50]
