Indexing and Slicing


In [1]:
import numpy as np


In [4]:
three_dim = np.reshape(np.arange(12), (3,2,2))
three_dim


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [5]:
three_dim[0,1,1]

np.int64(3)

In [6]:
three_dim[2,-1,-1]

np.int64(11)

In [7]:
one_dim = np.arange(10)
one_dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
one_dim[2:6]


array([2, 3, 4, 5])

In [9]:
one_dim[-1]

np.int64(9)

In [11]:
one_dim[-3:]

array([7, 8, 9])