Intrinsic NumPy array Creation

In [1]:
import numpy as np

In [2]:
integer_array = np.arange(10)
integer_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
sec_int = np.arange(100,120)
sec_int

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [5]:
random_num = np.random.rand(4,4)
random_num

array([[0.31873966, 0.15823945, 0.47958573, 0.31116728],
       [0.64254432, 0.70276104, 0.16340181, 0.29559821],
       [0.0612291 , 0.05763697, 0.02808554, 0.82759495],
       [0.34638276, 0.72131837, 0.49926634, 0.08259622]])

In [14]:
random_int = np.random.randint(0,100,4)
random_int

array([54, 80, 67, 16])

Creating Arrays filled with constant values

In [16]:
first_zero_arrays = np.zeros(5)
first_zero_arrays

array([0., 0., 0., 0., 0.])

In [18]:
first_ones_array = np.ones(5)
first_ones_array

array([1., 1., 1., 1., 1.])

In [19]:
first_ones_multi_dim = np.ones((2,4), dtype=int)
first_ones_multi_dim

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
first_empty_array = np.empty(5)
first_empty_array

array([1., 1., 1., 1., 1.])

In [21]:
first_empty_array_type = np.empty(10, dtype=int)
first_empty_array_type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
first_empty_array_type.fill(12)
first_empty_array_type

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [25]:
first_full_array = np.full((2,2), 8, dtype=float)
first_full_array

array([[8., 8.],
       [8., 8.]])