Joining and Splitting arrays

In [1]:
import numpy as np

In [3]:
first_arr = np.arange(1,11)
second_arr = np.arange(11,21)

con_arr = np.concatenate((first_arr, second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
stack_arr = np.stack((first_arr,second_arr))

stack_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [7]:
hstack_Arr = np.hstack((first_arr,second_arr))
hstack_Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
vstack_arr = np.vstack((first_arr, second_arr))
vstack_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Splitting Arrays

- Splitting breaks one array into multiple subarrays.
- functions -> `split`, `array_split`, `hsplit`, `vsplit`

Major drawback
- Will split only whne number of elements is divisible by number of splits. So the resulting arrays needs to have same shape.

In [9]:
new_arr = np.arange(1,13)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
split_arr = np.split(new_arr, 4)
split_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]