Array Types and conversions between types

In [4]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 43.1 MB/s  0:00:00
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:



integer = np.array([10,20,30,40,50])
print(integer)



[10 20 30 40 50]


In [9]:
print(integer[0])

integer[0]=21.5
integer



10


array([21, 20, 30, 40, 50])

In [10]:
floats = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print(floats.dtype)

float64


In [14]:
multi_dim = np.array([
    [[1, 2], [1, 2]], 
    [[2, 1], [2, 1]]
    ])
print(multi_dim.shape)

(2, 2, 2)


Creating Arrays from Lists and other Python structures


In [15]:
first_list=[1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
first_array = np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
second_list = [1,2,3, -1.23, 4.56]
second_array = np.array(second_list)
second_array

array([ 1.  ,  2.  ,  3.  , -1.23,  4.56])

In [19]:
third_list = ['Anna', 1000, 'Pete', 2000, 'John', 3000]
third_array = np.array(third_list)
third_array.dtype

dtype('<U21')

In [22]:
# array from tuples

first_tuple = (1,2,3,4,5)
arr_from_tuples = np.array(first_tuple)
arr_from_tuples

array([1, 2, 3, 4, 5])