How to get Unique Items and Counts

In [1]:
import numpy as np

In [5]:
first_arr = np.array([1,2,3,4,5,6,7,8,12,3,4,5,6,65])



In [6]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 65])

In [7]:
second_arr = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [8]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [11]:
np.unique(second_arr, axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [12]:
np.unique(first_arr, return_index= True)



(array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 65]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 13]))

In [ ]:
np.unique(second_arr, return_counts=True)
# frequency count of elements

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))